[project]
name = "gul-jamon-gamedev-intro"
version = "0.1.0"
description = "Introducción al desarrollo de videojuegos en pygame para la GUL Jamón (game jam)."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]
